// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CAnimate: typeof import('./src/components/C-Animate.vue')['default']
    CPullRefresh: typeof import('./src/components/C-PullRefresh.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Lesson: typeof import('./src/components/Lesson.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MasonPlan: typeof import('./src/components/MasonPlan.vue')['default']
    Plan: typeof import('./src/components/Plan.vue')['default']
    PullDown: typeof import('./src/components/PullDown.vue')['default']
    PullRefresh: typeof import('./src/components/PullRefresh.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    T: typeof import('./src/components/T.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    Three: typeof import('./src/components/Three.vue')['default']
    ThreeBoxGeometry: typeof import('./src/components/Three-BoxGeometry.vue')['default']
    ThreeGlb: typeof import('./src/components/Three-Glb.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
